version: 2
jobs:
  abas:
    docker:
      - image: python:3.8

    steps:
    - checkout
    - run: sleep 2s && apt update -y
    - run: ls && apt update -y
    - run: sleep 2s
    - run: ls && sleep 2s
    - run: sleep 2s


workflows:
  version: 2
  abas:
    jobs:
    - abas
